### ISSUE TITLE
refactoring-api 요청의 텍스트 형식의 문제

### ISSUE THREAD

**Issue by ChoiJangSeop** [skkuse/2024spring_41class_team7#26]
refactor-api 요청시 함깨 보내는 body를 text이므로, escape character(\t, \n...)가 모두 공백으로 인식되어야 합니다. 그런데 json.stringify를 통해 json 형식으로 보내게 되면 escape character를 일반적인 문자로만 인식합니다.

refactor-api에 요청 보낼때 바디의 텍스트는 반드시 **텍스트 그대로** 넣어주셔야 합니다!!!

- `body = json.stringify(input_code)` -> 🙅 
- `body=input_code` -> 😄

**Comment by jaebin-code** [comment]
해결했습니다!
